services:
  web_app:
    container_name: dashboard_web_app
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app
      - ./data:/app/data
    environment:
      - JWT_SECRET=super-secret-control-room-key-9912
    restart: always